package com.unilever.ohub.spark.acm.model

// Data Model: OPR_ORIG_INTEGRATION_ID can be misleading for Ohub 2.0
// as this will contain the new OHUB_OPERATOR_ID and OPR_LNKD_INTEGRATION_ID will contain OPERATOR_CONCAT_ID
case class AcmContactPerson(
    CP_ORIG_INTEGRATION_ID: String,
    CP_LNKD_INTEGRATION_ID: String,
    OPR_ORIG_INTEGRATION_ID: String,
    GOLDEN_RECORD_FLAG: String,
    WEB_CONTACT_ID: Option[String],
    EMAIL_OPTOUT: Option[String],
    PHONE_OPTOUT: Option[String],
    FAX_OPTOUT: Option[String],
    MOBILE_OPTOUT: Option[String],
    DM_OPTOUT: Option[String],
    LAST_NAME: Option[String],
    FIRST_NAME: Option[String],
    MIDDLE_NAME: Option[String],
    TITLE: Option[String],
    GENDER: Option[String],
    LANGUAGE: Option[String],
    EMAIL_ADDRESS: Option[String],
    MOBILE_PHONE_NUMBER: Option[String],
    PHONE_NUMBER: Option[String],
    FAX_NUMBER: Option[String],
    STREET: Option[String],
    HOUSENUMBER: Option[String],
    ZIPCODE: Option[String],
    CITY: Option[String],
    COUNTRY: Option[String],
    DATE_CREATED: Option[String],
    DATE_UPDATED: Option[String],
    DATE_OF_BIRTH: Option[String],
    PREFERRED: Option[String],
    ROLE: Option[String],
    COUNTRY_CODE: String,
    SCM: Option[String],
    DELETE_FLAG: String,
    KEY_DECISION_MAKER: Option[String],
    OPT_IN: Option[String],
    OPT_IN_DATE: Option[String],
    CONFIRMED_OPT_IN: Option[String],
    CONFIRMED_OPT_IN_DATE: Option[String],
    MOB_OPT_IN: Option[String],
    MOB_OPT_IN_DATE: Option[String],
    MOB_CONFIRMED_OPT_IN: Option[String],
    MOB_CONFIRMED_OPT_IN_DATE: Option[String],
    MOB_OPT_OUT_DATE: Option[String],
    ORG_FIRST_NAME: Option[String],
    ORG_LAST_NAME: Option[String],
    ORG_EMAIL_ADDRESS: Option[String],
    ORG_FIXED_PHONE_NUMBER: Option[String],
    ORG_MOBILE_PHONE_NUMBER: Option[String],
    ORG_FAX_NUMBER: Option[String]
)
