package com.unilever.ohub.spark.acm.model

// Data Model: OPR_ORIG_INTEGRATION_ID can be misleading for Ohub 2.0 as this will contain the new
// OHUB_OPERATOR_ID and OPR_LNKD_INTEGRATION_ID will contain OPERATOR_CONCAT_ID
case class AcmOperator(
    OPR_ORIG_INTEGRATION_ID: String,
    OPR_LNKD_INTEGRATION_ID: String,
    GOLDEN_RECORD_FLAG: String,
    COUNTRY_CODE: String,
    NAME: Option[String],
    CHANNEL: Option[String],
    SUB_CHANNEL: Option[String],
    ROUTE_TO_MARKET: Option[String],
    REGION: Option[String],
    OTM: Option[String],
    PREFERRED_PARTNER: Option[String],
    STREET: Option[String],
    HOUSE_NUMBER: Option[String],
    ZIPCODE: Option[String],
    CITY: Option[String],
    COUNTRY: Option[String],
    AVERAGE_SELLING_PRICE: Option[Double],
    NUMBER_OF_COVERS: Option[Int],
    NUMBER_OF_WEEKS_OPEN: Option[Int],
    NUMBER_OF_DAYS_OPEN: Option[Int],
    CONVENIENCE_LEVEL: Option[String],
    RESPONSIBLE_EMPLOYEE: Option[String],
    NPS_POTENTIAL: Option[BigDecimal],
    CAM_KEY: Option[String],
    CAM_TEXT: Option[String],
    CHANNEL_KEY: Option[String],
    CHANNEL_TEXT: Option[String],
    CHAIN_KNOTEN: Option[String],
    CHAIN_NAME: Option[String],
    CUST_SUB_SEG_EXT: Option[String],
    CUST_SEG_EXT: Option[String],
    CUST_SEG_KEY_EXT: Option[String],
    CUST_GRP_EXT: Option[String],
    PARENT_SEGMENT: Option[String],
    DATE_CREATED: Option[String],
    DATE_UPDATED: Option[String],
    DELETE_FLAG: String,
    WHOLESALER_OPERATOR_ID: Option[String],
    PRIVATE_HOUSEHOLD: Option[String],
    VAT: Option[String],
    OPEN_ON_MONDAY: Option[String],
    OPEN_ON_TUESDAY: Option[String],
    OPEN_ON_WEDNESDAY: Option[String],
    OPEN_ON_THURSDAY: Option[String],
    OPEN_ON_FRIDAY: Option[String],
    OPEN_ON_SATURDAY: Option[String],
    OPEN_ON_SUNDAY: Option[String],
    KITCHEN_TYPE: Option[String],
    LOCAL_CHANNEL: Option[String] = None,
    CHANNEL_USAGE: Option[String] = None,
    SOCIAL_COMMERCIAL: Option[String] = None,
    STRATEGIC_CHANNEL: Option[String] = None,
    GLOBAL_CHANNEL: Option[String] = None,
    GLOBAL_SUBCHANNEL: Option[String] = None
)
