image: timvancann/miniconda3-gcc

pipelines:
  default:
    - step:
        name: Test building EGG
        script:
          - conda env create -f environment.yml
          - source activate name-matching
          - ./compile_library.sh
