# Check https://confluence.atlassian.com/x/x4UWN for more examples.
# Validator: https://bitbucket-pipelines.atlassian.io/validator

image: python:3.6.6
clone:
  depth: 1
options:
  docker: true

pipelines:
  default:
    - step: &blackfmt
        name: Black formatting
        script:
          - pip install black
          - make black
    - step: &pycodestyle
        name: Pycodestyle
        script:
          - pip install .[dev]
          - make pycodestyle
    - step: &pylint
        name: Pylint
        script:
          - pip install .[dev]
          - make lint
    - step: &pytest
        name: Pytest
        script:
          - pip install .[dev]
          - make pytest
    - step: &dockerlint
        name: Dockerlint
        script:
          - make dockerlint
    - step: &dags
        name: Verify DAG integrity
        image:
          name: ulohubimages.azurecr.io/airflow_base:118
          username: ulohubimages
          password: $AZ_CONTAINER_REGISTRY_PASSWORD
        script:
          - bash ./test.sh
    - step: &docker
        name: Build image
        script:
          - docker login ulohubimages.azurecr.io -u ${AZ_CONTAINER_REGISTRY_USER_ID} -p ${AZ_CONTAINER_REGISTRY_PASSWORD}
          - docker build --tag ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER} --label "GIT_HASH=${BITBUCKET_COMMIT}" --file docker/airflow/Dockerfile .
          - docker tag ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER} ulohubimages.azurecr.io/airflow:latest
          - docker login ulohubimages.azurecr.io -u ${AZ_CONTAINER_REGISTRY_USER_ID} -p ${AZ_CONTAINER_REGISTRY_PASSWORD}
          - docker push ulohubimages.azurecr.io/airflow:latest
          - docker push ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER}

  branches:
    master:
    - step: *blackfmt
    - step: *pycodestyle
    - step: *pylint
    - step: *pytest
    - step: *dockerlint
    - step: *dags
    - step: *docker
    - step:
        name: Deploy Airflow in kubernetes Azure
        image: microsoft/azure-cli
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - az acs kubernetes install-cli
          - az aks get-credentials -g bieno-da-s-60072-containers-rg -n ul-ohub2-aks-dev-we

          - airflowimage="ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER}"
          - kubectl set image deployment/airflow-webserver webserver=${airflowimage}
          - kubectl set image deployment/airflow-scheduler scheduler=${airflowimage}
