# Check https://confluence.atlassian.com/x/x4UWN for more examples.
# Validator: https://bitbucket-pipelines.atlassian.io/validator

pipelines:
  default:
    - step: &pycodestyle
        name: pycodestyle
        script:
          - pip install .[dev]
          - make pycodestyle
    - step: &pylint
        name: pylint
        image: python:3.6.6
        script:
          - pip install pylint
          - make lint
    - step: &pytest
        name: Pytest
        script:
          - pip install .[dev]
          - make pytest

  branches:
    master:
    - step: *pycodestyle
    - step: *pylint
    - step: *pytest
    - step:
        name: Deploy to azure file share
        image: microsoft/azure-cli
        deployment: production
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - az storage file upload-batch --source . --destination airflow-dags --account-key ${AZ_AIRFLOW_STORAGE_KEY} --account-name ${AZ_AIRFLOW_STORAGE_ACCOUNT}
