clone:
  depth: 1

options:
  docker: true

pipelines:
  default:
    - step: &syntax
        name: Check PEP8 codestyle and run tests
        image: timvancann/miniconda3-gcc
        script:
          - bash ./lint.sh
    - step: &dags
        name: Verify DAG integrity
        image:
          name: ulohubimages.azurecr.io/airflow:latest
          username: ulohubimages
          password: $AZ_CONTAINER_REGISTRY_PASSWORD
        script:
          - bash ./test.sh

  branches:
    master:
    - step: *syntax
    - step: *dags
    - step:
        name: Deploy to azure file share
        image: microsoft/azure-cli
        deployment: production
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - az storage file upload-batch --source dags/ --destination airflow-dags --account-key ${AZ_AIRFLOW_STORAGE_KEY} --account-name ${AZ_AIRFLOW_STORAGE_ACCOUNT}

  custom:
    build-airflow-image:
      - step:
          name: Dockerlint
          script:
            - make dockerlint
      - step:
          name: Build image
          script:
            - docker build -f docker/airflow/Dockerfile .
