# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: Check PEP8 codestyle and run tests
        image: python:3.5.1
        caches:
          - pip
        script:
          - pip install pycodestyle pytest requests_mock
          - pytest tests
          - pycodestyle --show-source .

  branches:
    master:
    - step:
        name: Check PEP8 codestyle and run tests
        image: python:3.5.1
        caches:
          - pip
        script:
          - pip install pycodestyle pytest requests_mock
          - pytest tests
          - pycodestyle --show-source .
    - step:
        name: Deploy to azure blob store
        image: microsoft/azure-cli
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - rm -rf README.md bitbucket-pipelines.yml .gitignore setup.cfg
          - tar -cvf dags.tar .
          - az storage blob upload -f dags.tar -c prod -n deployment/airflow/dags/dags.tar --account-key ${AZ_STORAGE_KEY} --account-name ${AZ_STORAGE_ACCOUNT}

    dev:
    - step:
        name: Check PEP8 codestyle and run tests
        image: python:3.5.1
        caches:
          - pip
        script:
          - pip install pycodestyle pytest requests_mock
          - pytest tests
          - pycodestyle --show-source .
    - step:
        name: Deploy to azure blob store
        image: microsoft/azure-cli
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - rm -rf README.md bitbucket-pipelines.yml .gitignore setup.cfg
          - tar -cvf dags.tar .
          - az storage blob upload -f dags.tar -c dev -n deployment/airflow/dags/dags.tar --account-key ${AZ_STORAGE_KEY} --account-name ${AZ_STORAGE_ACCOUNT}
