# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  default:
    - step:
        name: Check PEP8 codestyle and run tests
        image: timvancann/miniconda3-gcc
        script:
          - conda env create -f environment.yml
          - source activate airflow-dags
          - pycodestyle --show-source .
          - python -m pytest --cov-config .coveragerc --cov=./dags tests

  branches:
    master:
    - step:
        name: Check PEP8 codestyle and run tests
        image: timvancann/miniconda3-gcc
        script:
          - conda env create -f environment.yml
          - source activate airflow-dags
          - pycodestyle --show-source .
          - python -m pytest --cov-config .coveragerc --cov=./dags tests
    - step:
        name: Deploy to azure file share
        image: microsoft/azure-cli
        deployment: production
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - az storage file upload-batch --source dags/ --destination airflow-dags --account-key ${AZ_AIRFLOW_STORAGE_KEY} --account-name ${AZ_AIRFLOW_STORAGE_ACCOUNT}
