
pipelines:
  default:
    - step:
        name: Test building EGG
        image: timvancann/miniconda3-gcc
        script:
          - conda env create -f environment.yml
          - source activate name-matching
          - ./compile_library.sh
  branches:
    master:
    - step:
        name: Build EGG
        image: timvancann/miniconda3-gcc
        script:
          - conda env create -f environment.yml
          - source activate name-matching
          - ./compile_library.sh
        artifacts:
          - dist/*.egg
    - step:
        name: Deploy to gcloud bucket
        image: google/cloud-sdk:latest
        script:
          - echo $G_SECRET > key.json
          - gcloud auth activate-service-account bitbucket@ufs-prod.iam.gserviceaccount.com --key-file=key.json
          - gsutil cp dist/*.egg gs://ufs-prod/deployment/name-matching/dist/
          - gsutil cp *.py gs://ufs-prod/deployment/name-matching/
