
pipelines:
  default:
    - step:
        name: Test building EGG
        image: timvancann/miniconda3-gcc
        script:
          - conda env create -f environment.yml
          - source activate name-matching
          - ./compile_library.sh
  branches:
    master:
    - step:
        name: Build EGG
        image: timvancann/miniconda3-gcc
        script:
          - conda env create -f environment.yml
          - source activate name-matching
          - ./compile_library.sh
        artifacts:
          - dist/*.egg
    - step:
        name: Deploy to gcloud bucket
        image: google/cloud-sdk:latest
        script:
          - echo $G_SECRET > key.json
          - gcloud auth activate-service-account bitbucket@ufs-prod.iam.gserviceaccount.com --key-file=key.json
          - gsutil cp dist/*.egg gs://ufs-prod/deployment/name-matching/dist/
          - gsutil cp *.py gs://ufs-prod/deployment/name-matching/
    - step:
        name: Deploy to azure blob store
        image: microsoft/azure-cli
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - az storage blob upload -f dist/string_matching.egg -c prod -n deployment/name-matching/dist/string_matching.egg --account-key ${AZ_STORAGE_KEY} --account-name ${AZ_STORAGE_ACCOUNT}
          - az storage blob upload -f match_operators.py -c prod -n deployment/name-matching/match_operators.py --account-key ${AZ_STORAGE_KEY} --account-name ${AZ_STORAGE_ACCOUNT}
    - step:
        name: Deploy to databricks fs
        image: timvancann/databricks-cli
        script:
          - touch ~/.databrickscfg
          - echo "[DEFAULT]" >> ~/.databrickscfg
          - echo "host = ${DB_HOST}" >> ~/.databrickscfg
          - echo "token = ${DB_TOKEN}" >> ~/.databrickscfg
          - cat ~/.databrickscfg
          - databricks fs rm dbfs:/libraries/string_matching.egg
          - databricks fs rm dbfs:/libraries/match_operators.py
          - databricks fs cp dist/string_matching.egg dbfs:/libraries/string_matching.egg
          - databricks fs cp match_operators.py dbfs:/libraries/match_operators.py

