image: timvancann/miniconda3-gcc

pipelines:
  default:
    - step:
        name: Test building EGG
        script:
          - conda env create -f environment.yml
          - source activate name-matching
          - ./compile_library.sh
  branches:
    master:
    - step:
        name: Build EGG
        script:
          - conda env create -f environment.yml
          - source activate name-matching
          - ./compile_library.sh
        artifacts:
          - dist/*.egg
    - step:
        name: Deploy to cluster
        script:
          - ssh hdiuser@edgenodeappx.ulohubhddevne5-ssh.azurehdinsight.net 'mkdir -p ~/deployment/name-matching/'
          - mkdir -p ~/deployment/name-matching/dist
          - scp dist/*.egg hdiuser@edgenodeappx.ulohubhddevne5-ssh.azurehdinsight.net:~/deployment/name-matching/dist/
          - scp *.py hdiuser@edgenodeappx.ulohubhddevne5-ssh.azurehdinsight.net:~/deployment/name-matching/
