# Check https://confluence.atlassian.com/x/x4UWN for more examples.
# Validator: https://bitbucket-pipelines.atlassian.io/validator

clone:
  depth: 1

options:
  docker: true

pipelines:
  default:
    - step: &test
        name: test
        image:
          name: ulohubimages.azurecr.io/airflow_base:120
          username: ulohubimages
          password: $AZ_CONTAINER_REGISTRY_PASSWORD
        script:
          - pwd
          - ls /opt/atlassian/pipelines/agent/build/
          - ls /root/
          - airflow initdb
          - pip install .[dev]
          - make black
          - make pycodestyle
          - make lint
          - make pytest
          - make dockerlint
    - step: &docker
        name: Build image
        script:
        - docker login ulohubimages.azurecr.io -u ${AZ_CONTAINER_REGISTRY_USER_ID} -p ${AZ_CONTAINER_REGISTRY_PASSWORD}
        - docker build --tag ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER} --label "GIT_HASH=${BITBUCKET_COMMIT}" --file docker/airflow/Dockerfile .
        - docker tag ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER} ulohubimages.azurecr.io/airflow:latest
        - docker login ulohubimages.azurecr.io -u ${AZ_CONTAINER_REGISTRY_USER_ID} -p ${AZ_CONTAINER_REGISTRY_PASSWORD}
        - docker push ulohubimages.azurecr.io/airflow:latest
        - docker push ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER}

  branches:
    master:
    - step: *test
    - step: *docker
    - step:
        name: Deploy Airflow in kubernetes Azure
        image: microsoft/azure-cli
        script:
          - az login --service-principal -u ${AZ_USER_ID} -p ${AZ_PASSWORD} --tenant ${AZ_TENANT_ID}
          - az acs kubernetes install-cli
          - az aks get-credentials -g bieno-da-s-60072-containers-rg -n ul-ohub2-aks-dev-we

          - airflowimage="ulohubimages.azurecr.io/airflow:${BITBUCKET_BUILD_NUMBER}"
          - kubectl set image deployment/airflow-webserver webserver=${airflowimage}
          - kubectl set image deployment/airflow-scheduler scheduler=${airflowimage}
