name: airflow-dags
channels:
  - defaults
  - conda-forge
dependencies:
  - azure-storage-blob=1.3.1
  - azure=1.0.2
  - google-api-python-client=1.6.7
  - pandas-gbq=0.5.0
  - paramiko=2.4.1
  - pytest-mock=1.10.0
  - pytest=3.6.3
  - python=3.6.6
  - pip:
    - apache-airflow[crypto]==1.9.0
