from airflow import DAG
from datetime import datetime, timedelta

from custom_operators.ga_fetch_operator import GAFetchOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email': ['airflow@airflow.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 5,
    'retry_delay': timedelta(minutes=2),
    'start_date': datetime.now(),
    'date_from': datetime.now().strftime('%Y%m%d'),
    'date_to': datetime.now().strftime('%Y%m%d'),
    'bigquery_conn_id': 'gcp_ga',
    'destination_folder': 'gs://digitaldataufs/ga_dump',
    'country_codes': [
        'AU',
        'NZ',
        'BE',
        'FR',
        'NL',
        # CN,
        'AT',
        'DE',
        'CH',
        # IN,
        'IL',
        'GR',
        'IT',
        'MQ',
        'LK',
        'PK',
        'SA',
        'HK',
        'TW',
        # KR,
        'CA',
        'US',
        'CZ',
        'SK',
        'EE',
        'PL',
        'CO',
        'MX',
        # LA,
        # DK,
        'FI',
        'NO',
        # SE,
        'PT',
        'RU',
        'ZA',
        'ID',
        'MY',
        # PH,
        'SG',
        'TH',
        'VN',
        'BG',
        'HU',
        'RO',
        'AR',
        'BR',
        'CL',
        'ES',
        'TR',
        'IE',
        'GB',
    ],
}

dag = DAG('gcp_ga', default_args=default_args)

ga_to_avro = GAFetchOperator(task_id="perform_ga_fetch",
                             dag=dag,
                             bigquery_conn_id=default_args.get(
                                 'bigquery_conn_id'),
                             country_codes=default_args.get('coutry_codes'),
                             date_from=default_args.get('date_from'),
                             date_to=default_args.get('date_to'),
                             destination_folder=default_args.get(
                                 'destination_folder'))
