name: name-matching
channels:
  - defaults
dependencies:
  - python=3.5.4
  - wheel=0.30.0
  - cython=0.27.3
  - numpy=1.14.0
  - setuptools=38.4.0=py35_0
  - scipy==1.0.0
  - pandas==0.22.0
  - pytest==2.8.5
  - pycodestyle==2.3.1
  - pytest-cov==2.5.1
  - pytest-runner==4.2.0
