name: name-matching
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.1
  - wheel=0.32.3
  - cython=0.29.2
  - numpy=1.15.4
  - setuptools=40.6.3=py37_0
  - scipy==1.1.0
  - pandas==0.23.4
  - pytest==4.0.2
  - pycodestyle==2.4.0
  - pytest-cov==2.7.1
  - pytest-mock==1.10.4
  - pytest-runner==5.1
