name: name-matching
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.4
  - wheel=0.33.6
  - cython=0.29.12
  - numpy=1.17.0
  - setuptools=41.1.0
  - scipy==1.3.1
  - pandas==0.25.0
  - pytest==5.1.1
  - pycodestyle==2.5.0
  - pytest-cov==2.7.1
  - pytest-mock==1.10.4
  - pytest-runner==5.1
