package com.unilever.ohub.spark.export.ddl

import java.sql.Timestamp

import com.unilever.ohub.spark.SparkJobSpec
import com.unilever.ohub.spark.domain.entity.TestOperatorsGolden
import com.unilever.ohub.spark.export.ddl.model.DdlOperator

class OperatorDdlConverterSpec extends SparkJobSpec with TestOperatorsGolden {


  val SUT = OperatorDdlConverter
  val operatorToConvert = defaultOperatorGolden.copy(ohubId = Some("12345"),
    globalChannel = Some("globalChannel"), customerHierarchyLevel3 = Some("customerHierarchyLevel3"),
    customerHierarchyLevel4 = Some("customerHierarchyLevel4"),
    customerHierarchyLevel5 = Some("customerHierarchyLevel5"),
    customerHierarchyLevel7 = Some("customerHierarchyLevel7"), latitude = Some("latitude"),
    longitude = Some("longitude"), isIndirectAccount = Some(true), salesGroupKey = Some("salesGroupKey"), salesOfficeKey = Some("salesOfficeKey"),
    industryKey = Some("industryKey"),
    salesDistrict = Some("salesDistrict"),
    customerGroup = Some("customerGroup"),
    languageKey = Some("languageKey"), sapCustomerId = Some("sapCustomerId"),
    recordType = Some("recordType"),
    keyNumber = Some("keyNumber"), hasWebshopAccount = Some("hasWebshopAccount"),
    daysOpenPerWeek = Some(1),
    hasOutsideSeatings = Some(true),
    hasTakeAway = Some(false),
    hasHomeDelivery = Some(false),
    numberOfSeats = Some(1),
    numberOfBedsRange = Some("numberOfBedsRange"),
    numberOfRoomsRange = Some("numberOfRoomsRange"),
    numberOfStudentsRange = Some("numberOfStudentsRange"),
    totalStaffRange = Some("totalStaffRange"),
    hasFoodOnsite = Some(true),
    hasConference = Some(true),
    twitterUrl = Some("twitterUrl"),
    facebookUrl = Some("facebookUrl"),
    instagramUrl = Some("instagramUrl"),
    numberOfChildSites = Some(3),
    lastWebLoginDate = Some(Timestamp.valueOf("2021-02-12 11:11:11")),
    lastOpenedNewsletterDate = Some(Timestamp.valueOf("2021-02-12 11:11:11")),
    subcribedToUfsNewsletter = Some("subcribedToUfsNewsletter"),
    subcribedToIceCreamNewsletter = Some("subcribedToIceCreamNewsletter"),
    last3OnlineEvents = Some("last3OnlineEvents"), totalFacebookCampaignsClicked = Some(3),
    livechatActivities = Some("livechatActivities"),
    totalLoyaltyRewardsBalancePoints = Some(3),
    loyaltyRewardsBalanceUpdatedDate = Some(Timestamp.valueOf("2021-02-12 11:11:11")),
    accountSubType = Some("accountSubType"),
    visitorsPerYear = Some("visitorsPerYear"),
    unileverNowClassification = Some("unileverNowClassification"),
    tradingStatus = Some("tradingStatus"), hasPermittedToOrder = Some(true))

  describe("operator ddl converter") {
    it("should convert a domain operator correctly into an ddl operator") {

      val result = SUT.convert(operatorToConvert)

      val expectedDdlOperator = DdlOperator(
        `AFH Customer Golden ID` = "12345",
        `CRM Account ID` = "",
        `Customer SAP concat ID` = "source-entity-id",
        Channel = "",
        Division = "",
        SalesOrgID = "",
        ParentSourceCustomerCode = "",
        `Closing Time Working Day` = "",
        `Opening Time Working Day` = "",
        `Preferred Visit Days` = "",
        `Preferred Visit Start Time` = "",
        `Preferred Visit End Time` = "",
        `Preferred Delivery Day/s` = "",
        `Preferred Visit week of Month` = "",
        `Customer Name` = "operator-name",
        `Customer Name 2` = "",
        `Address Line 1` = "street",
        City = "city",
        State = "state",
        `Postal Code` = "1234 AB",
        Country = "country-name",
        Region = "region",
        `Phone Number 1` = "+31123456789",
        Fax = "+31123456789",
        Email = "email-address@some-server.com",
        OTM = "D",
        `OTM Reason` = "otm-entered-by",
        Segment = "channel",
        `Sub Segments` = "sub-channel",
        `Parent Segment` = "",
        `Account Type` = "",
        `Account Status` = "",
        `Webshop Registered` = "",
        `Loyalty Management Opt In` = "",
        `Number of meal served per day` = "150",
        `Avg. Price per Meal` = "12345.00",
        `Week/Year Open` = "4",
        `Food Spend Month` = "",
        `Convenience Level` = "cooking-convenience-level",
        Latitude = "latitude",
        Longitude = "longitude",
        `Customer Hierarchy Level 3 Desc` = "customerHierarchyLevel3",
        `Customer Hierarchy Level 4 Desc` = "customerHierarchyLevel4",
        `Customer Hierarchy Level 5 Desc` = "customerHierarchyLevel5",
        `Customer Hierarchy Level 7 Desc` = "customerHierarchyLevel7",
        MixedorUFS = "",
        SalesGroupKey = "salesGroupKey",
        SalesOfficeKey = "salesOfficeKey",
        ECCIndustryKey = "industryKey",
        SalesDistrict = "salesDistrict",
        CustomerGroup = "customerGroup",
        `Language Key` = "languageKey",
        `SAP Customer ID` = "sapCustomerId",
        `Record Type` = "recordType",
        `Indirect Account` = "Y",
        SourceName = "source-name",
        Website = "www.google.com",
        `Key Number` = "keyNumber",
        `Has Webshop Account` = "hasWebshopAccount",
        `Day Week Open` = "1",
        `Do you have a terrace / outside seating?` = "Y",
        `Do you offer takeaways?` = "N",
        `Do you offer a home delivery service?` = "N",
        `How many seats do you have?` = "1",
        `Kitchen Type` = "kitchen-type",
        `Number of Beds (Range) - Site` = "numberOfBedsRange",
        `Number of Rooms (Range) - Site` = "numberOfRoomsRange",
        `Number of Students/Pupils (Range) - Site` = "numberOfStudentsRange",
        `Number of Employees (Range) - Group` = "totalStaffRange",
        `Food Served Onsite` = "Y",
        `Conference Outlet On Site` = "Y",
        `Twitter URL` = "twitterUrl",
        `Facebook URL` = "facebookUrl",
        `Instagram URL` = "instagramUrl",
        `Number of child sites` = "3",
        `Last login to website` = "2021-02-12 11:11:11:000",
        `Last newsletter opened` = "2021-02-12 11:11:11:000",
        `Subcribed to UFS newsletter` = "subcribedToUfsNewsletter",
        `Subcribed to Ice Cream newsletter` = "subcribedToIceCreamNewsletter",
        `Last 3 online events` = "last3OnlineEvents",
        `Facebook campaigns clicked` = "3",
        `LiveChat activities` = "livechatActivities",
        `Loyalty Rewards Balance Points` = "3",
        `Loyalty Rewards Balance updated Date` = "2021-02-12 11:11:11:000",
        `Account Sub Type` = "accountSubType",
        `Visitors per year` = "visitorsPerYear",
        `Unilever Now Classification` = "unileverNowClassification",
        `Trading Status` = "tradingStatus",
        CTPS = "",
        `Caterlyst Opportunity` = "",
        `Rep Assessed Opportunity` = "",
        `OTM OOH Calculated` = "",
        `OTM UFS Calculated` = "",
        `E-OTM` = "",
        `Relative lead score` = "",
        `Permitted to order` = "Y",
        `OFS value` = "",
        `RtM IC flag` = ""
      )
      result shouldBe expectedDdlOperator
    }
  }

}
