package com.unilever.ohub.spark.export.ddl.model

import com.unilever.ohub.spark.export.DDLOutboundEntity

case class DdlOperator(
                        `AFH Customer Golden ID`: String,
                        `CRM Account ID`: String,
                        `Customer SAP concat ID`: String,
                        Channel: String,
                        Division: String,
                        SalesOrgID: String,
                        ParentSourceCustomerCode: String,
                        `Closing Time Working Day`: String,
                        `Opening Time Working Day`: String,
                        `Preferred Visit Days`: String,
                        `Preferred Visit Start Time`: String,
                        `Preferred Visit End Time`: String,
                        `Preferred Delivery Day/s`: String,
                        `Preferred Visit week of Month`: String,
                        `Customer Name`: String,
                        `Customer Name 2`: String,
                        `Address Line 1`: String,
                        City: String,
                        State: String,
                        `Postal Code`: String,
                        Country: String,
                        Region: String,
                        `Phone Number 1`: String,
                        Fax: String,
                        Email: String,
                        OTM: String,
                        `OTM Reason`: String,
                        Segment: String,
                        `Sub Segments`: String,
                        `Parent Segment`: String,
                        `Account Type`: String,
                        `Account Status`: String,
                        `Webshop Registered`: String,
                        `Loyalty Management Opt In`: String,
                        `Number of meal served per day`: String,
                        `Avg. Price per Meal`: String,
                        `Week/Year Open`: String,
                        `Food Spend Month`: String,
                        `Convenience Level`: String,
                        Latitude: String,
                        Longitude: String,
                        `Customer Hierarchy Level 3 Desc`: String,
                        `Customer Hierarchy Level 4 Desc`: String,
                        `Customer Hierarchy Level 5 Desc`: String,
                        `Customer Hierarchy Level 7 Desc`: String,
                        MixedorUFS: String,
                        SalesGroupKey: String,
                        SalesOfficeKey: String,
                        ECCIndustryKey: String,
                        SalesDistrict: String,
                        CustomerGroup: String,
                        `Language Key`: String,
                        `SAP Customer ID`: String,
                        `Record Type`: String,
                        `Indirect Account`: String,
                        SourceName: String,
                        Website: String,
                        `Key Number`: String,
                        `Has Webshop Account`: String,
                        `Day Week Open`: String,
                        `Do you have a terrace / outside seating?`: String,
                        `Do you offer takeaways?`: String,
                        `Do you offer a home delivery service?`: String,
                        `How many seats do you have?`: String,
                        `Kitchen Type`: String,
                        `Number of Beds (Range) - Site`: String,
                        `Number of Rooms (Range) - Site`: String,
                        `Number of Students/Pupils (Range) - Site`: String,
                        `Number of Employees (Range) - Group`: String,
                        `Food Served Onsite`: String,
                        `Conference Outlet On Site`: String,
                        `Twitter URL`: String,
                        `Facebook URL`: String,
                        `Instagram URL`: String,
                        `Number of child sites`: String,
                        `Last login to website`: String,
                        `Last newsletter opened`: String,
                        `Subcribed to UFS newsletter`: String,
                        `Subcribed to Ice Cream newsletter`: String,
                        `Last 3 online events`: String,
                        `Facebook campaigns clicked`: String,
                        `LiveChat activities`: String,
                        `Loyalty Rewards Balance Points`: String,
                        `Loyalty Rewards Balance updated Date`: String,
                        `Account Sub Type`: String,
                        `Visitors per year`: String,
                        `Unilever Now Classification`: String,
                        `Trading Status`: String,
                        CTPS: String,
                        `Caterlyst Opportunity`: String,
                        `Rep Assessed Opportunity`: String,
                        `OTM OOH Calculated`: String,
                        `OTM UFS Calculated`: String,
                        `E-OTM`: String,
                        `Relative lead score`: String,
                        `Permitted to order`: String,
                        `OFS value`: String,
                        `RtM IC flag`: String
                      ) extends DDLOutboundEntity
