package com.unilever.ohub.spark.export.acm.model

import com.unilever.ohub.spark.export.OutboundEntity

case class AcmContactPerson(
                             CP_ORIG_INTEGRATION_ID: String,
                             CP_LNKD_INTEGRATION_ID: String,
                             OPR_ORIG_INTEGRATION_ID: String,
                             GOLDEN_RECORD_FLAG: String,
                             WEB_CONTACT_ID: String = "",
                             EMAIL_OPTOUT: String,
                             PHONE_OPTOUT: String,
                             FAX_OPTOUT: String,
                             MOBILE_OPTOUT: String,
                             DM_OPTOUT: String,
                             LAST_NAME: String,
                             FIRST_NAME: String,
                             MIDDLE_NAME: String = "",
                             TITLE: String,
                             GENDER: String,
                             LANGUAGE: String,
                             EMAIL_ADDRESS: String,
                             MOBILE_PHONE_NUMBER: String,
                             PHONE_NUMBER: String,
                             FAX_NUMBER: String,
                             STREET: String,
                             HOUSENUMBER: String,
                             ZIPCODE: String,
                             CITY: String,
                             COUNTRY: String,
                             DATE_CREATED: String,
                             DATE_UPDATED: String,
                             DATE_OF_BIRTH: String,
                             PREFERRED: String,
                             ROLE: String,
                             COUNTRY_CODE: String,
                             SCM: String,
                             DELETE_FLAG: String,
                             KEY_DECISION_MAKER: String,
                             OPT_IN: String,
                             OPT_IN_DATE: String,
                             CONFIRMED_OPT_IN: String,
                             CONFIRMED_OPT_IN_DATE: String,
                             MOB_OPT_IN: String,
                             MOB_OPT_IN_DATE: String,
                             MOB_CONFIRMED_OPT_IN: String,
                             MOB_CONFIRMED_OPT_IN_DATE: String,
                             MOB_OPT_OUT_DATE: String = "",
                             ORG_FIRST_NAME: String,
                             ORG_LAST_NAME: String,
                             ORG_EMAIL_ADDRESS: String,
                             ORG_FIXED_PHONE_NUMBER: String,
                             ORG_MOBILE_PHONE_NUMBER: String,
                             ORG_FAX_NUMBER: String,
                             HAS_REGISTRATION: String,
                             REGISTRATION_DATE: String,
                             HAS_CONFIRMED_REGISTRATION: String,
                             CONFIRMED_REGISTRATION_DATE: String,
                             TARGET_OHUB_ID: String
                           ) extends OutboundEntity
