package com.unilever.ohub.spark.export.ddl

import java.sql.Timestamp

import com.unilever.ohub.spark.domain.entity.Operator
import com.unilever.ohub.spark.export._
import com.unilever.ohub.spark.export.ddl.model.DdlOperator

object OperatorDdlConverter extends Converter[Operator, DdlOperator] with TypeConversionFunctions {
  // scalastyle:off method.length
  override def convert(implicit op: Operator, explain: Boolean = false): DdlOperator = {
    DdlOperator(
      id = getValue("id"),
      concatId = getValue("concatId"),
      countryCode = getValue("countryCode"),
      customerType = getValue("customerType"),
      dateCreated = getValue("dateCreated"),
      dateUpdated = getValue("dateUpdated"),
      isActive = getValue("isActive", BooleanToYNConverter),
      isGoldenRecord = getValue("isGoldenRecord", BooleanToYNConverter),
      ohubId = getValue("ohubId"),
      name = getValue("name"),
      sourceEntityId = getValue("sourceEntityId"),
      sourceName = getValue("sourceName"),
      ohubCreated = getValue("ohubCreated"),
      ohubUpdated = getValue("ohubUpdated"),
      annualTurnover = getValue("annualTurnover"),
      averagePrice = getValue("averagePrice"),
      averageRating = getValue("averageRating"),
      beveragePurchasePotential = getValue("beveragePurchasePotential"),
      buildingSquareFootage = getValue("buildingSquareFootage"),
      chainId = getValue("chainId"),
      chainName = getValue("chainName"),
      channel = getValue("channel"),
      city = getValue("city"),
      cookingConvenienceLevel = getValue("cookingConvenienceLevel"),
      countryName = getValue("countryName"),
      daysOpen = getValue("daysOpen"),
      distributorName = getValue("distributorName"),
      distributorOperatorId = getValue("distributorOperatorId"),
      emailAddress = getValue("emailAddress"),
      faxNumber = getValue("faxNumber"),
      hasDirectMailOptIn = getValue("hasDirectMailOptIn", BooleanToYNConverter),
      hasDirectMailOptOut = getValue("hasDirectMailOptOut", BooleanToYNConverter),
      hasEmailOptIn = getValue("hasEmailOptIn", BooleanToYNConverter),
      hasEmailOptOut = getValue("hasEmailOptOut", BooleanToYNConverter),
      hasFaxOptIn = getValue("hasFaxOptIn", BooleanToYNConverter),
      hasFaxOptOut = getValue("hasFaxOptOut", BooleanToYNConverter),
      hasGeneralOptOut = getValue("hasGeneralOptOut", BooleanToYNConverter),
      hasMobileOptIn = getValue("hasMobileOptIn", BooleanToYNConverter),
      hasMobileOptOut = getValue("hasMobileOptOut", BooleanToYNConverter),
      hasTelemarketingOptIn = getValue("hasTelemarketingOptIn", BooleanToYNConverter),
      hasTelemarketingOptOut = getValue("hasTelemarketingOptOut", BooleanToYNConverter),
      headQuarterAddress = getValue("headQuarterAddress"),
      headQuarterCity = getValue("headQuarterCity"),
      headQuarterPhoneNumber = getValue("headQuarterPhoneNumber"),
      headQuarterState = getValue("headQuarterState"),
      headQuarterZipCode = getValue("headQuarterZipCode"),
      houseNumber = getValue("houseNumber"),
      houseNumberExtension = getValue("houseNumberExtension"),
      isNotRecalculatingOtm = getValue("isNotRecalculatingOtm", BooleanToYNConverter),
      isOpenOnFriday = getValue("isOpenOnFriday", BooleanToYNConverter),
      isOpenOnMonday = getValue("isOpenOnMonday", BooleanToYNConverter),
      isOpenOnSaturday = getValue("isOpenOnSaturday", BooleanToYNConverter),
      isOpenOnSunday = getValue("isOpenOnSunday", BooleanToYNConverter),
      isOpenOnThursday = getValue("isOpenOnThursday", BooleanToYNConverter),
      isOpenOnTuesday = getValue("isOpenOnTuesday", BooleanToYNConverter),
      isOpenOnWednesday = getValue("isOpenOnWednesday", BooleanToYNConverter),
      isPrivateHousehold = getValue("isPrivateHousehold", BooleanToYNConverter),
      kitchenType = getValue("kitchenType"),
      menuKeywords = getValue("menuKeywords"),
      mobileNumber = getValue("mobileNumber"),
      netPromoterScore = getValue("netPromoterScore"),
      numberOfProductsFittingInMenu = getValue("numberOfProductsFittingInMenu"),
      numberOfReviews = getValue("numberOfReviews"),
      oldIntegrationId = getValue("oldIntegrationId"),
      operatorLeadScore = getValue("operatorLeadScore"),
      otm = getValue("otm"),
      otmEnteredBy = getValue("otmEnteredBy"),
      phoneNumber = getValue("phoneNumber"),
      potentialSalesValue = getValue("potentialSalesValue"),
      region = getValue("region"),
      salesRepresentative = getValue("salesRepresentative"),
      state = getValue("state"),
      street = getValue("street"),
      subChannel = getValue("subChannel"),
      totalDishes = getValue("totalDishes"),
      totalLocations = getValue("totalLocations"),
      totalStaff = getValue("totalStaff"),
      vat = getValue("vat"),
      wayOfServingAlcohol = getValue("wayOfServingAlcohol"),
      website = getValue("website"),
      webUpdaterId = getValue("webUpdaterId"),
      weeksClosed = getValue("weeksClosed"),
      yearFounded = getValue("yearFounded"),
      zipCode = getValue("zipCode"),
      localChannel = getValue("localChannel"),
      channelUsage = getValue("channelUsage"),
      socialCommercial = getValue("socialCommercial"),
      strategicChannel = getValue("strategicChannel"),
      globalChannel = getValue("globalChannel"),
      globalSubChannel = getValue("globalSubChannel"),
      ufsClientNumber = getValue("ufsClientNumber"),
      department = getValue("department")
    )
  }
}
