package com.unilever.ohub.spark.export.ddl

import com.unilever.ohub.spark.domain.entity.OperatorGolden
import com.unilever.ohub.spark.export._
import com.unilever.ohub.spark.export.ddl.model.DdlOperator

object OperatorDdlConverter extends Converter[OperatorGolden, DdlOperator] with TypeConversionFunctions {

  // scalastyle:off method.length
  override def convert(implicit op: OperatorGolden, explain: Boolean = false): DdlOperator = {
    DdlOperator(
      `AFH Customer Golden ID` = getValue("ohubId"),
      `CRM Account ID` = getValue("crmId"),
      `Customer SAP concat ID` = getValue("sourceEntityId"),
      Channel = getValue("distributionChannel"),
      Division = getValue("division"),
      SalesOrgID = getValue("salesOrgId"),
      ParentSourceCustomerCode = getValue("parentSourceCustomerCode"),
      `Closing Time Working Day` = getValue("closingTimeWorkingDay"),
      `Opening Time Working Day` = getValue("openingTimeWorkingDay"),
      `Preferred Visit Days` = getValue("preferredVisitDays"),
      `Preferred Visit Start Time` = getValue("preferredVisitStartTime"),
      `Preferred Visit End Time` = getValue("preferredVisitEndTime"),
      `Preferred Delivery Day/s` = getValue("preferredDeliveryDays"),
      `Preferred Visit week of Month` = getValue("preferredVisitWeekOfMonth"),
      `Customer Name` = getValue("name"),
      `Customer Name 2` = getValue("name2"),
      `Address Line 1` = getValue("street"),
      City = getValue("city"),
      State = getValue("state"),
      `Postal Code` = getValue("zipCode"),
      Country = getValue("countryName"),
      Region = getValue("region"),
      `Phone Number 1` = getValue("phoneNumber"),
      Fax = getValue("faxNumber"),
      Email = getValue("emailAddress"),
      OTM = getValue("otm"),
      `OTM Reason` = getValue("otmEnteredBy"),
      Segment = getValue("channel"),
      `Sub Segments` = getValue("subChannel"),
      `Parent Segment` = getValue("parentChannel"),
      `Account Type` = getValue("accountType"),
      `Account Status` = getValue("accountStatus"),
      `Webshop Registered` = getValue("hasWebshopRegistration"),
      `Loyalty Management Opt In` = getValue("hasLoyaltyManagementOptIn"),
      `Number of meal served per day` = getValue("totalDishes"),
      `Avg. Price per Meal` = getValue("averagePrice"),
      `Week/Year Open` = getValue("daysOpen"),
      `Food Spend Month` = getValue("monthlyFoodSpend"),
      `Convenience Level` = getValue("cookingConvenienceLevel"),
      Latitude = getValue("latitude"),
      Longitude = getValue("longitude"),
      `Customer Hierarchy Level 3 Desc` = getValue("customerHierarchyLevel3"),
      `Customer Hierarchy Level 4 Desc` = getValue("customerHierarchyLevel4"),
      `Customer Hierarchy Level 5 Desc` = getValue("customerHierarchyLevel5"),
      `Customer Hierarchy Level 7 Desc` = getValue("customerHierarchyLevel7"),
      MixedorUFS = getValue("mixedOrUfs"),
      SalesGroupKey = getValue("salesGroupKey"),
      SalesOfficeKey = getValue("salesOfficeKey"),
      ECCIndustryKey = getValue("industryKey"),
      SalesDistrict = getValue("salesDistrict"),
      CustomerGroup = getValue("customerGroup"),
      `Language Key` = getValue("languageKey"),
      `SAP Customer ID` = getValue("sapCustomerId"),
      `Record Type` = getValue("recordType"),
      `Indirect Account` = getValue("isIndirectAccount"),
      SourceName = getValue("sourceName"),
      Website = getValue("website"),
      `Key Number` = getValue("keyNumber"),
      `Has Webshop Account` = getValue("hasWebshopAccount"),
      `Day Week Open` = getValue("daysOpenPerWeek"),
      `Do you have a terrace / outside seating?` = getValue("hasOutsideSeatings"),
      `Do you offer takeaways?` = getValue("hasTakeAway"),
      `Do you offer a home delivery service?` = getValue("hasHomeDelivery"),
      `How many seats do you have?` = getValue("numberOfSeats"),
      `Kitchen Type` = getValue("kitchenType"),
      `Number of Beds (Range) - Site` = getValue("numberOfBedsRange"),
      `Number of Rooms (Range) - Site` = getValue("numberOfRoomsRange"),
      `Number of Students/Pupils (Range) - Site` = getValue("numberOfStudentsRange"),
      `Number of Employees (Range) - Group` = getValue("totalStaffRange"),
      `Food Served Onsite` = getValue("hasFoodOnsite"),
      `Conference Outlet On Site` = getValue("hasConference"),
      `Twitter URL` = getValue("twitterUrl"),
      `Facebook URL` = getValue("facebookUrl"),
      `Instagram URL` = getValue("instagramUrl"),
      `Number of child sites` = getValue("numberOfChildSites"),
      `Last login to website` = getValue("lastWebLoginDate"),
      `Last newsletter opened` = getValue("lastOpenedNewsletterDate"),
      `Subcribed to UFS newsletter` = getValue("subcribedToUfsNewsletter"),
      `Subcribed to Ice Cream newsletter` = getValue("subcribedToIceCreamNewsletter"),
      `Last 3 online events` = getValue("last3OnlineEvents"),
      `Facebook campaigns clicked` = getValue("totalFacebookCampaignsClicked"),
      `LiveChat activities` = getValue("livechatActivities"),
      `Loyalty Rewards Balance Points` = getValue("totalLoyaltyRewardsBalancePoints"),
      `Loyalty Rewards Balance updated Date` = getValue("loyaltyRewardsBalanceUpdatedDate"),
      `Account Sub Type` = getValue("accountSubType"),
      `Visitors per year` = getValue("visitorsPerYear"),
      `Unilever Now Classification` = getValue("unileverNowClassification"),
      `Trading Status` = getValue("tradingStatus"),
      CTPS = getValue("hasTelephoneSuppressed"),
      `Caterlyst Opportunity` = getValue("caterlystPotentialTurnover"),
      `Rep Assessed Opportunity` = getValue("salesRepEstimatedPotentialTurnover"),
    `OTM OOH Calculated` = getValue("otmOohCalculated"),
    `OTM UFS Calculated` = getValue("otmUfsCalculated"),
    `E-OTM` = getValue("eOtm"),
    `Relative lead score` = getValue("relativeLeadScore"),
    `Permitted to order` = getValue("hasPermittedToOrder"),
    `OFS value` = getValue("ofsValue"),
    `RtM IC flag` = getValue("routeToMarketIceCreamCategory")
    )
  }
}
