package com.unilever.ohub.spark.ingest.common

import java.sql.Timestamp

import com.unilever.ohub.spark.domain.entity.Operator
import com.unilever.ohub.spark.ingest.CsvDomainGateKeeperSpec

class OperatorConverterSpec extends CsvDomainGateKeeperSpec[Operator] {

  override val SUT = OperatorConverter

  describe("common operator converter") {
    it("should convert an operator correctly from a valid common csv input") {
      val inputFile = "src/test/resources/COMMON_OPERATORS.csv"

      runJobWith(inputFile) { actualDataSet ⇒
        actualDataSet.count() shouldBe 6

        import com.unilever.ohub.spark.SharedSparkSession.spark
        import spark.implicits._

        val actualOperator = actualDataSet.filter($"id" === "id-3").head()

        val expectedOperator = Operator(
          id = "id-3",
          creationTimestamp = new Timestamp(1542205922011L),
          concatId = "TR~KANGAROO~HG_226466866",
          countryCode = "TR",
          customerType = "OPERATOR",
          dateCreated = Some(Timestamp.valueOf("2017-12-18 10:47:37")),
          dateUpdated = Some(Timestamp.valueOf("2017-12-18 10:47:37")),
          isActive = true,
          isGoldenRecord = false,
          name = Some("Kebapçim Ali - Bodrum"),
          sourceName = "KANGAROO",
          sourceEntityId = "HG_226466866",
          ohubId = actualOperator.ohubId,
          ohubCreated = actualOperator.ohubCreated,
          ohubUpdated = actualOperator.ohubUpdated,
          annualTurnover = None,
          averagePrice = None,
          averageRating = None,
          beveragePurchasePotential = None,
          buildingSquareFootage = None,
          chainId = Some("UG_1"),
          chainName = Some("Diger Müsteriler"),
          channel = Some("Restaurants"),
          city = Some("Mugla"),
          cookingConvenienceLevel = None,
          countryName = Some("Turkey"),
          daysOpen = None,
          distributorName = None,
          distributorOperatorId = None,
          emailAddress = None,
          faxNumber = None,
          hasDirectMailOptIn = Some(true),
          hasDirectMailOptOut = None,
          hasEmailOptIn = Some(true),
          hasEmailOptOut = None,
          hasFaxOptIn = Some(true),
          hasFaxOptOut = None,
          hasGeneralOptOut = None,
          hasMobileOptIn = Some(true),
          hasMobileOptOut = None,
          hasTelemarketingOptIn = Some(true),
          hasTelemarketingOptOut = None,
          headQuarterAddress = None,
          headQuarterCity = None,
          headQuarterPhoneNumber = None,
          headQuarterState = None,
          headQuarterZipCode = None,
          houseNumber = None,
          houseNumberExtension = None,
          isNotRecalculatingOtm = None,
          isOpenOnFriday = Some(true),
          isOpenOnMonday = Some(true),
          isOpenOnSaturday = Some(true),
          isOpenOnSunday = None,
          isOpenOnThursday = Some(true),
          isOpenOnTuesday = Some(true),
          isOpenOnWednesday = Some(true),
          isPrivateHousehold = None,
          kitchenType = None,
          menuKeywords = None,
          mobileNumber = Some("05356800669"),
          netPromoterScore = Some(BigDecimal("0")),
          numberOfProductsFittingInMenu = None,
          numberOfReviews = None,
          oldIntegrationId = None,
          operatorLeadScore = None,
          otm = None,
          otmEnteredBy = None,
          phoneNumber = Some("0252 3854478"),
          potentialSalesValue = None,
          region = Some("Mugla"),
          salesRepresentative = Some("Bodrum (Vacant)"),
          state = Some("Bodrum"),
          street = Some("Yalikavak Mahallesi, Çökertme Caddesi, No 187, Bodrum, Mugla"),
          subChannel = Some("Kebapçi"),
          totalDishes = Some(120),
          totalLocations = None,
          totalStaff = None,
          vat = Some("18808137040"),
          wayOfServingAlcohol = None,
          website = None,
          webUpdaterId = None,
          weeksClosed = None,
          yearFounded = None,
          zipCode = None,
          localChannel = None,
          channelUsage = None,
          socialCommercial = None,
          strategicChannel = None,
          globalChannel = None,
          globalSubChannel = None,
          //CRM Fields
          crmFields = Operator.OperatorCRM(actualOperator.crmFields.crmAccountId,
            actualOperator.crmFields.division,
            actualOperator.crmFields.salesOrgId,
            actualOperator.crmFields.parentSourceCustomerCode,
            actualOperator.crmFields.closingTimeWorkingDay,
            actualOperator.crmFields.openingTimeWorkingDay,
            actualOperator.crmFields.preferredVisitDays,
            actualOperator.crmFields.preferredVisitStartTime,
            actualOperator.crmFields.preferredVisitEndTime,
            actualOperator.crmFields.preferredDeliveryDays,
            actualOperator.crmFields.preferredVisitWeekOfMonth,
            actualOperator.crmFields.name2,
            actualOperator.crmFields.accountType,
            actualOperator.crmFields.monthlyFoodSpend,
            actualOperator.crmFields.latitude,
            actualOperator.crmFields.longitude,
            actualOperator.crmFields.customerHierarchyLevel3,
            actualOperator.crmFields.customerHierarchyLevel4,
            actualOperator.crmFields.customerHierarchyLevel5,
            actualOperator.crmFields.customerHierarchyLevel7,
            actualOperator.crmFields.mixedOrUfs,
            actualOperator.crmFields.salesGroupKey,
            actualOperator.crmFields.salesOfficeKey,
            actualOperator.crmFields.industryKey,
            actualOperator.crmFields.salesDistrict,
            actualOperator.crmFields.customerGroup,
            actualOperator.crmFields.languageKey,
            actualOperator.crmFields.recordType,
            actualOperator.crmFields.isIndirectAccount,
            actualOperator.crmFields.keyNumber,
            actualOperator.crmFields.hasOutsideSeatings,
            actualOperator.crmFields.hasTakeAway,
            actualOperator.crmFields.hasHomeDelivery,
            actualOperator.crmFields.numberOfSeats,
            actualOperator.crmFields.numberOfBedsRange,
            actualOperator.crmFields.numberOfRoomsRange,
            actualOperator.crmFields.numberOfStudentsRange,
            actualOperator.crmFields.hasFoodOnsite,
            actualOperator.crmFields.hasConference,
            actualOperator.crmFields.twitterUrl,
            actualOperator.crmFields.facebookUrl,
            actualOperator.crmFields.instagramUrl,
            actualOperator.crmFields.numberOfChildSites,
            actualOperator.crmFields.totalFacebookCampaignsClicked,
            actualOperator.crmFields.accountSubType,
            actualOperator.crmFields.visitorsPerYear,
            actualOperator.crmFields.unileverNowClassification,
            actualOperator.crmFields.tradingStatus,
            actualOperator.crmFields.hasTelephoneSuppressed,
            actualOperator.crmFields.caterlystPotentialTurnover,
            actualOperator.crmFields.salesRepEstimatedPotentialTurnover,
            actualOperator.crmFields.preferredCommunicationMethod,
            actualOperator.crmFields.hasPermittedToShareSsd,
            actualOperator.crmFields.otmOohCalculated,
            actualOperator.crmFields.otmUfsCalculated
          ),
          additionalFields = Map(),
          ingestionErrors = Map(),
          ufsClientNumber = None,
          department = Some("UFS")
//          department = None
        )

        actualOperator shouldBe expectedOperator
      }
    }
  }
}
