package com.unilever.ohub.spark

object Constants {

  val CSV_PATTERN = "UFS_([A-Z0-9_-]+)_(CHAINS|LOYALTY|OPERATORS|OPERATOR_ACTIVITIES|OPERATOR_CLASSIFICATIONS|" +
    "CONTACTPERSONS|CONTACTPERSON_ACTIVITIES|CONTACTPERSON_CLASSIFICATIONS|CONTACTPERSON_SOCIAL|CONTACTPERSON_ANONYMIZATIONS|" +
    "PRODUCTS|ORDERS|ORDERLINES|ORDERS_DELETED|ORDERLINES_DELETED|SUBSCRIPTIONS|QUESTIONS|ANSWERS|CAMPAIGN_OPENS|" +
    "CAMPAIGN_CLICKS|CAMPAIGN_BOUNCES|CAMPAIGNS|CAMPAIGN_SENDS|CHANNEL_MAPPINGS|INVALID_EMAILS|INVALID_MOBILE_NUMBERS)_([0-9]{14}).csv"
}
