package com.unilever.ohub.spark.dispatcher
package model

import com.unilever.ohub.spark.domain.entity.ContactPerson

object DispatcherContactPerson {
  def fromContactPerson(cp: ContactPerson): DispatcherContactPerson = {
    DispatcherContactPerson(
      DATE_OF_BIRTH = cp.birthDate.mapWithDefaultPatternOpt,
      CITY = cp.city,
      CP_ORIG_INTEGRATION_ID = cp.concatId,
      COUNTRY_CODE = cp.countryCode,
      COUNTRY = cp.countryName,
      EMAIL_ADDRESS = cp.emailAddress,
      CONFIRMED_OPT_IN_DATE = cp.emailDoubleOptInDate.mapWithDefaultPatternOpt,
      OPT_IN_DATE = cp.emailOptInDate.mapWithDefaultPatternOpt,
      FAX_NUMBER = cp.faxNumber,
      GENDER = cp.gender,
      DM_OPT_OUT = cp.hasDirectMailOptOut,
      CONFIRMED_OPT_IN = cp.hasEmailDoubleOptIn,
      OPT_IN = cp.hasEmailOptIn,
      EMAIL_OPT_OUT = cp.hasEmailOptOut,
      FAX_OPT_OUT = cp.hasFaxOptOut,
      MOB_CONFIRMED_OPT_IN = cp.hasMobileDoubleOptIn,
      MOB_OPT_IN = cp.hasMobileOptIn,
      MOBILE_OPT_OUT = cp.hasMobileOptOut,
      FIXED_OPT_OUT = cp.hasTeleMarketingOptOut,
      HOUSE_NUMBER = cp.houseNumber,
      HOUSE_NUMBER_ADD = cp.houseNumberExtension,
      DELETE_FLAG = cp.isActive.invert,
      GOLDEN_RECORD_FLAG = cp.isGoldenRecord,
      KEY_DECISION_MAKER = cp.isKeyDecisionMaker,
      PREFERRED = cp.isPreferredContact,
      LANGUAGE = cp.language,
      LAST_NAME = cp.lastName,
      MOB_CONFIRMED_OPT_IN_DATE = cp.mobileDoubleOptInDate.mapWithDefaultPatternOpt,
      MOBILE_PHONE_NUMBER = cp.mobileNumber,
      MOB_OPT_IN_DATE = cp.mobileOptInDate.mapWithDefaultPatternOpt,
      CREATED_AT = cp.ohubCreated.mapWithDefaultPattern,
      CP_LNKD_INTEGRATION_ID = cp.ohubId,
      UPDATED_AT = cp.ohubUpdated.mapWithDefaultPattern,
      OPR_ORIG_INTEGRATION_ID = cp.operatorConcatId,
      FIXED_PHONE_NUMBER = cp.phoneNumber,
      SOURCE_ID = cp.sourceEntityId,
      SOURCE = cp.sourceName,
      SCM = cp.standardCommunicationChannel,
      STATE = cp.state,
      STREET = cp.street,
      TITLE = cp.title,
      ZIP_CODE = cp.zipCode,
      MIDDLE_NAME = Option.empty,
      ROLE = cp.jobTitle,
      ORG_FIRST_NAME = Option.empty,
      ORG_LAST_NAME = Option.empty,
      ORG_EMAIL_ADDRESS = Option.empty,
      ORG_FIXED_PHONE_NUMBER = Option.empty,
      ORG_MOBILE_PHONE_NUMBER = Option.empty,
      ORG_FAX_NUMBER = Option.empty,
      MOB_OPT_OUT_DATE = Option.empty
    )
  }
}

case class DispatcherContactPerson(
    DATE_OF_BIRTH: Option[String],
    CITY: Option[String],
    CP_ORIG_INTEGRATION_ID: String,
    COUNTRY_CODE: String,
    COUNTRY: Option[String],
    EMAIL_ADDRESS: Option[String],
    CONFIRMED_OPT_IN_DATE: Option[String],
    OPT_IN_DATE: Option[String],
    FAX_NUMBER: Option[String],
    GENDER: Option[String],
    DM_OPT_OUT: Option[Boolean],
    CONFIRMED_OPT_IN: Option[Boolean],
    OPT_IN: Option[Boolean],
    EMAIL_OPT_OUT: Option[Boolean],
    FAX_OPT_OUT: Option[Boolean],
    MOB_CONFIRMED_OPT_IN: Option[Boolean],
    MOB_OPT_IN: Option[Boolean],
    MOBILE_OPT_OUT: Option[Boolean],
    FIXED_OPT_OUT: Option[Boolean],
    HOUSE_NUMBER: Option[String],
    HOUSE_NUMBER_ADD: Option[String],
    DELETE_FLAG: Boolean,
    GOLDEN_RECORD_FLAG: Boolean,
    KEY_DECISION_MAKER: Option[Boolean],
    PREFERRED: Option[Boolean],
    LANGUAGE: Option[String],
    LAST_NAME: Option[String],
    MOB_CONFIRMED_OPT_IN_DATE: Option[String],
    MOBILE_PHONE_NUMBER: Option[String],
    MOB_OPT_IN_DATE: Option[String],
    CREATED_AT: String,
    CP_LNKD_INTEGRATION_ID: Option[String],
    UPDATED_AT: String,
    OPR_ORIG_INTEGRATION_ID: String,
    FIXED_PHONE_NUMBER: Option[String],
    SOURCE_ID: String,
    SOURCE: String,
    SCM: Option[String],
    STATE: Option[String],
    STREET: Option[String],
    TITLE: Option[String],
    ZIP_CODE: Option[String],
    MIDDLE_NAME: Option[String],
    ROLE: Option[String],
    ORG_FIRST_NAME: Option[String],
    ORG_LAST_NAME: Option[String],
    ORG_EMAIL_ADDRESS: Option[String],
    ORG_FIXED_PHONE_NUMBER: Option[String],
    ORG_MOBILE_PHONE_NUMBER: Option[String],
    ORG_FAX_NUMBER: Option[String],
    MOB_OPT_OUT_DATE: Option[String]
)
