package com.unilever.ohub.spark.export.dispatch.model

import com.unilever.ohub.spark.export.OutboundEntity

case class DispatchOrder(
    SOURCE_ID: String,
    ORD_INTEGRATION_ID: String,
    COUNTRY_CODE: String,
    SOURCE: String,
    DELETED_FLAG: String,
    CREATED_AT: String,
    UPDATED_AT: String,
    ORDER_TYPE: String,
    CP_ORIG_INTEGRATION_ID: String,
    OPR_ORIG_INTEGRATION_ID: String,
    WHOLESALER: String,
    WHOLESALER_ID: String,
    WHOLESALER_CUSTOMER_NUMBER: String,
    WHOLESALER_LOCATION: String,
    ORDER_EMAIL_ADDRESS: String = "",
    ORDER_PHONE_NUMBER: String = "",
    ORDER_MOBILE_PHONE_NUMBER: String = "",
    TRANSACTION_DATE: String,
    TOTAL_VALUE_ORDER_CURRENCY: String,
    TOTAL_VALUE_ORDER_AMOUNT: String,
    ORIGIN: String = "",
    WS_DC: String = "",
    ORDER_UID: String,
    CAMPAIGN_CODE: String,
    CAMPAIGN_NAME: String,
    DELIVERY_STREET: String,
    DELIVERY_HOUSE_NUMBER: String,
    DELIVERY_HOUSE_NUMBER_EXT: String,
    DELIVERY_POST_CODE: String,
    DELIVERY_CITY: String,
    DELIVERY_STATE: String,
    DELIVERY_COUNTRY: String,
    DELIVERY_PHONE: String = "",
    INVOICE_NAME: String,
    INVOICE_STREET: String,
    INVOICE_HOUSE_NUMBER: String,
    INVOICE_HOUSE_NUMBER_EXT: String,
    INVOICE_ZIPCODE: String,
    INVOICE_CITY: String,
    INVOICE_STATE: String,
    INVOICE_COUNTRY: String,
    COMMENTS: String,
    VAT: String) extends OutboundEntity

