package com.unilever.ohub.spark.export.dispatch.model

import com.unilever.ohub.spark.export.DispatcherOutboundEntity

case class DispatchOperator(
    COUNTRY_CODE: String,
    OPR_ORIG_INTEGRATION_ID: String,
    OPR_LNKD_INTEGRATION_ID: String,
    GOLDEN_RECORD_FLAG: String,
    SOURCE: String,
    SOURCE_ID: String,
    CREATED_AT: String,
    UPDATED_AT: String,
    DELETE_FLAG: String,
    NAME: String,
    CHANNEL: String,
    SUB_CHANNEL: String,
    ROUTE_TO_MARKET: String = "",
    REGION: String,
    OTM: String,
    PREFERRED_PARTNER: String,
    STREET: String,
    HOUSE_NUMBER: String,
    HOUSE_NUMBER_EXT: String,
    CITY: String,
    COUNTRY: String,
    ZIP_CODE: String,
    AVERAGE_SELLING_PRICE: String,
    NUMBER_OF_COVERS: String,
    NUMBER_OF_WEEKS_OPEN: String,
    NUMBER_OF_DAYS_OPEN: String,
    STATUS: String,
    CONVENIENCE_LEVEL: String,
    RESPONSIBLE_EMPLOYEE: String,
    NPS_POTENTIAL: String,
    CAM_KEY: String = "",
    CAM_TEXT: String = "",
    CHANNEL_KEY: String = "",
    CHANNEL_TEXT: String,
    CHAIN_KNOTEN: String,
    CHAIN_NAME: String,
    DM_OPT_OUT: String,
    EMAIL_OPT_OUT: String,
    FIXED_OPT_OUT: String,
    MOBILE_OPT_OUT: String,
    FAX_OPT_OUT: String,
    KITCHEN_TYPE: String,
    STATE: String,
    WHOLE_SALER_OPERATOR_ID: String,
    PRIVATE_HOUSEHOLD: String,
    VAT: String,
    OPEN_ON_MONDAY: String,
    OPEN_ON_TUESDAY: String,
    OPEN_ON_WEDNESDAY: String,
    OPEN_ON_THURSDAY: String,
    OPEN_ON_FRIDAY: String,
    OPEN_ON_SATURDAY: String,
    OPEN_ON_SUNDAY: String,
    LOCAL_CHANNEL: String,
    CHANNEL_USAGE: String,
    SOCIAL_COMMERCIAL: String,
    STRATEGIC_CHANNEL: String,
    GLOBAL_CHANNEL: String,
    GLOBAL_SUBCHANNEL: String
) extends DispatcherOutboundEntity
