package com.unilever.ohub.spark.export.dispatch.model

import com.unilever.ohub.spark.export.OutboundEntity

case class DispatchContactPerson(
    COUNTRY_CODE: String,
    CP_ORIG_INTEGRATION_ID: String,
    CP_LNKD_INTEGRATION_ID: String,
    GOLDEN_RECORD_FLAG: String,
    SOURCE: String,
    SOURCE_ID: String,
    DELETE_FLAG: String,
    CREATED_AT: String,
    UPDATED_AT: String,
    GENDER: String,
    ROLE: String,
    TITLE: String,
    FIRST_NAME: String,
    MIDDLE_NAME: String = "",
    LAST_NAME: String,
    STREET: String,
    HOUSE_NUMBER: String,
    HOUSE_NUMBER_ADD: String,
    ZIP_CODE: String,
    CITY: String,
    COUNTRY: String,
    DM_OPT_OUT: String,
    EMAIL_ADDRESS: String,
    EMAIL_OPT_OUT: String,
    FIXED_OPT_OUT: String,
    FIXED_PHONE_NUMBER: String,
    MOBILE_OPT_OUT: String,
    MOBILE_PHONE_NUMBER: String,
    LANGUAGE: String,
    PREFERRED: String,
    KEY_DECISION_MAKER: String,
    FAX_OPT_OUT: String,
    FAX_NUMBER: String,
    DATE_OF_BIRTH: String,
    SCM: String,
    STATE: String,
    OPT_IN: String,
    OPT_IN_DATE: String,
    CONFIRMED_OPT_IN: String,
    CONFIRMED_OPT_IN_DATE: String,
    OPR_ORIG_INTEGRATION_ID: String,
    ORG_FIRST_NAME: String = "",
    ORG_LAST_NAME: String = "",
    ORG_EMAIL_ADDRESS: String = "",
    ORG_FIXED_PHONE_NUMBER: String = "",
    ORG_MOBILE_PHONE_NUMBER: String = "",
    ORG_FAX_NUMBER: String = "",
    MOB_OPT_IN: String,
    MOB_OPT_IN_DATE: String,
    MOB_CONFIRMED_OPT_IN: String,
    MOB_CONFIRMED_OPT_IN_DATE: String,
    MOB_OPT_OUT_DATE: String = ""
) extends OutboundEntity
