@startuml
title Entity can be run after...

[ContactPersons] as CP
[Operators] as OP
[Orders] as OD
[Orderlines] as OL
[Products] as PD
[Activities] as AC
[Questions] as QU
[Answers] as AN
[Subscriptions] as SC
[LoyaltyPoints] as LP

[Campaign] as CMP
[CampaignClicks] as CMPC
[CampaignBounces] as CMPB
[CampaignSends] as CMPS
[CampaignOpens] as CMPO

CP --> OP

OD --> CP

OL ----> PD

AC --> CP

QU --> AC

AN --> QU

SC --> CP

LP --> CP

CMP ---> CP
CMPC ---> CP
CMPB ---> CP
CMPS ---> CP
CMPO ---> CP

@enduml